max_width = 100
use_small_heuristics = "Max"
wrap_comments = true
comment_width = 100
format_code_in_doc_comments = true
normalize_doc_attributes = true
group_imports = "StdExternalCrate"
imports_granularity = "Item"
reorder_imports = true
newline_style = "Unix"

