openapi: 3.0.0
info:
  title: GitHub API
  version: 1.0.0
servers:
  - url: https://api.github.com
paths:
  /user:
    get:
      operationId: get-user
      summary: Get authenticated user information
      description: Get current user
      tags: [github]
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
              example:
                login: octocat
                id: 1
                name: The Octocat
      x-auth:
        scheme: oauth2
        injection:
          type: jsonada
          mapping: |
            {
              "Authorization": "Bearer " & $access_token,
              "Accept": "application/vnd.github+json",
              "User-Agent": "openact-test/1.0"
            }
      x-ok-path: "$status >= 200 and $status < 300"
      x-output-pick: "$body"
      x-timeout-ms: 5000
      x-retry:
        max_retries: 3
        retry_on: ["5xx", "429"]
      x-real-http: true
