openapi: 3.0.0
info:
  title: GitHub API (Mocked)
  version: 1.0.0
servers:
  - url: https://api.github.com
paths:
  /user:
    get:
      operationId: getUser
      summary: Get authenticated user (mocked)
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
              example:
                login: octocat
                id: 1
                name: The Octocat
      x-output-pick: "$body"
      x-simulate-statuses: [200]
