openapi: 3.0.0
info:
  title: GitHub API
  version: 1.0.0
servers:
  - url: https://api.github.com
paths:
  /repos/{owner}/{repo}/issues:
    get:
      operationId: list-issues
      summary: List Issues
      description: List issues in a repository
      tags: [github]
      parameters:
        - name: owner
          in: path
          description: Repository owner (username or organization)
          required: true
          schema:
            type: string
        - name: repo
          in: path
          description: Repository name
          required: true
          schema:
            type: string
        - name: state
          in: query
          description: Issue state (open, closed, all)
          required: false
          schema:
            type: string
            default: open
        - name: labels
          in: query
          description: Comma-separated list of label names
          required: false
          schema:
            type: string
        - name: sort
          in: query
          description: Sort by created, updated, comments
          required: false
          schema:
            type: string
            default: created
        - name: direction
          in: query
          description: Sort direction (asc or desc)
          required: false
          schema:
            type: string
            default: desc
        - name: per_page
          in: query
          description: Number of results per page (max 100)
          required: false
          schema:
            type: integer
            default: 30
        - name: page
          in: query
          description: Page number of results to fetch
          required: false
          schema:
            type: integer
            default: 1
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
      x-auth:
        scheme: oauth2
        injection:
          type: jsonada
          mapping: |
            {
              "Authorization": "Bearer " & $access_token,
              "Accept": "application/vnd.github+json",
              "User-Agent": "openact/1.0"
            }
      x-ok-path: "$status >= 200 and $status < 300"
      x-output-pick: "$body"
      x-timeout-ms: 5000
      x-retry:
        max_retries: 3
        retry_on: ["5xx", "429"]
      x-real-http: true
