openapi: 3.0.0
info:
  title: Mock HTTP
  version: 1.0.0
paths:
  /upload:
    post:
      operationId: upload
      summary: Multipart upload
      requestBody:
        required: false
        content:
          multipart/form-data:
            schema:
              type: object
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
      x-real-http: true
      x-output-pick: "$body"
      x-ok-path: "$status >= 200 and $status < 300"
      x-url: "http://127.0.0.1:8091/upload"
      x-transform-pre:
        - |-
          {% { 'body': $body } %}
