#!/bin/bash

# GitHub OAuth2 真实授权演示脚本

echo "🚀 GitHub OAuth2 真实授权演示"
echo "=============================="
echo ""
echo "📋 当前执行状态:"
echo "   执行 ID: f51eb1be-4817-4633-a26f-e8e41c08e1c4"
echo "   状态: paused (等待用户授权)"
echo ""
echo "🔗 授权 URL:"
echo "https://github.com/login/oauth/authorize?response_type=code&client_id=Ov23lihVkExosE0hR0Bh&redirect_uri=http%3A%2F%2Flocalhost%3A8080%2Foauth%2Fcallback&scope=user%3Aemail&state=ECZvY2jGzKmwtWlW3ADzM1wI&code_challenge_method=S256&code_challenge=T_-XjiL0caNtD_vARbfxyC6PSA4dVvfjuMEN2Wp2rRw"
echo ""
echo "📝 操作步骤:"
echo "   1. 在浏览器中访问上面的授权 URL"
echo "   2. 登录你的 GitHub 账户"
echo "   3. 授权应用访问你的账户信息"
echo "   4. GitHub 会重定向到: http://localhost:8080/oauth/callback?code=授权码&state=ECZvY2jGzKmwtWlW3ADzM1wI"
echo "   5. 从 URL 中复制授权码（code 参数的值）"
echo ""
echo "💡 注意: 由于我们使用的是 localhost:8080 作为回调 URL，"
echo "   你需要确保 openact 服务器正在运行以接收回调。"
echo ""
echo "🔄 当你获得授权码后，可以运行以下命令继续流程:"
echo "   curl -X POST \"http://localhost:8080/api/v1/executions/f51eb1be-4817-4633-a26f-e8e41c08e1c4/resume\" \\"
echo "     -H \"Content-Type: application/json\" \\"
echo "     -d '{\"input\": {\"code\": \"你的授权码\"}}'"
echo ""
echo "📊 然后检查执行状态:"
echo "   curl -s \"http://localhost:8080/api/v1/executions/f51eb1be-4817-4633-a26f-e8e41c08e1c4\" | jq '.status'"
echo ""
echo "🔍 检查数据库中的连接记录:"
echo "   curl -s \"http://localhost:8080/api/v1/connections?tenant=test-tenant&provider=github\" | jq '.'"
echo ""
echo "🎯 这将完成完整的 GitHub OAuth2 流程，包括:"
echo "   ✓ 用户授权"
echo "   ✓ 授权码交换"
echo "   ✓ 用户信息获取"
echo "   ✓ 连接信息持久化到数据库"
